apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service  # Debe coincidir con las etiquetas del pod
  ports:
    - protocol: TCP
      port: 80         # Puerto externo del servicio
      targetPort: 5000   # Puerto interno del contenedor
